### ISSUE TITLE
Recovery keys from muon are not working

### ISSUE THREAD

**Issue by NejcZdovc** [brave-intl/bat-native-ledger#40]
If you try to recover wallet from muon it fails.

I tried with `just initial park scene frog stand vintage black love close noodle hunt siren amateur combine lawsuit blouse addict faculty must piano dirt ivory alert` (generated in muon)

and HKDF returns different result in muon then it returns in core

muon implementation: https://github.com/brave/crypto/blob/master/index.js#L126
![image](https://user-images.githubusercontent.com/9574457/43900244-8cb01980-9be4-11e8-8369-57060523d1cd.png)

core implementation: https://github.com/brave-intl/bat-native-ledger/blob/master/src/bat_helper.cc#L1240
![image](https://user-images.githubusercontent.com/9574457/43900268-a0f41680-9be4-11e8-9769-3cab691bf346.png)

**Comment by SergeyZhukovsky** [comment]
@gdregalo fixed it here https://github.com/brave-intl/bat-native-ledger/pull/53
